[package]
name = "log-sloth"
version = "0.2.0"
authors = ["Xavier Lange <xrlange@gmail.com>"]

[dependencies]
ctrlc = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
nom-syslog = "*"
nom = "*"
log = "*"
env_logger = "*"
pretty-bytes = "*"
rusoto_core = { git = "https://github.com/rusoto/rusoto", branch = "master" }
rusoto_kinesis = { git = "https://github.com/rusoto/rusoto", branch = "master" }
prctl = "*"
futures = "*"
tokio-core = "*"
tokio-io = "*"
tokio-proto = "*"
tokio-service = "*"
bytes = "*"
time = "*"

[profile.release]
lto = true
debug = true
