[package]
name = "log-sloth"
version = "0.1.0"
authors = ["Xavier Lange <xrlange@gmail.com>"]

[dependencies]
ctrlc = "*"
rusoto_core = "*"
rusoto_kinesis = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"