[package]
name = "log-sloth"
version = "0.2.0"
authors = ["Xavier Lange <xrlange@gmail.com>"]

[dependencies]
ctrlc = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
nom-syslog = "*"
nom = "*"
log = "*"
env_logger = "*"
pretty-bytes = "*"
rusoto_core = { path = "/Users/xlange/code/viasat/rusoto-async/rusoto/core" }# { git = "https://github.com/srijs/rusoto-async", branch = "master" } # "*"
rusoto_kinesis = { path = "/Users/xlange/code/viasat/rusoto-async/rusoto/services/kinesis" } # { git = "https://github.com/srijs/rusoto-async", branch = "master" } # "*"
prctl = "*"
futures = "*"

[profile.release]
lto = true
debug = true
