FROM debian:jessie
ADD docker/perf.list /etc/apt/sources.list.d/perf.list
RUN apt-get update && \
    apt-get install -y \
    htop vim sysstat net-tools aptitude \
    linux-perf linux-perf-4.4 \
    ca-certificates
ADD target/log-sloth \
    /usr/local/bin/
CMD /usr/local/bin/log-sloth

